# Uncomment the next line to define a global platform for your project
platform :ios, '18.0'

target 'KmmApple' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ReactiveObjC', '3.1.1'

   # ... other dependencies ...
   pod 'FusionPod', :path => '../kmm/apps/fusion/'


  # Pods for KmmApple

  target 'KmmAppleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KmmAppleUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
    end
  end
end
